name: cns
base: core18
version: '1.0.0'
summary: cns
description: cns
grade: stable
confinement: strict
layout:
  /var/lib/cns-node:
    bind: $SNAP_DATA/var/lib/cns-node
parts:
  cns-node:
    plugin: go
    source-type: git
    source: git@github.com:cryptonetworking/cns.git
apps:
  longlogd:
    daemon: simple
    command: cns node -addr 0.0.0.0:9999 -dir /var/lib/cns-node
    stop-timeout: 10m
    stop-mode: sigterm
    install-mode: enable
    plugs:
      - network-bind