name: cryptoname
base: core18
version: '1.0.0'
summary: cryptoname
description: cryptoname
grade: stable
confinement: strict
layout:
  /var/lib/crpyotname-node:
    bind: $SNAP_DATA/var/lib/cryptoname-node
parts:
  crpyotname:
    plugin: go
    source-type: git
    source: git@github.com:cryptonetworking/cryptoname.git
apps:
  cryptons:
    command: cryptoname
    plugs:
      - network-bind
  crpyotname-node:
    daemon: simple
    command: cryptoname node -addr 0.0.0.0:9999 -dir /var/lib/cryptoname-node
    stop-timeout: 10m
    stop-mode: sigterm
    install-mode: enable
    plugs:
      - network-bind